// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'order_detail.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

OrderDetail _$OrderDetailFromJson(Map<String, dynamic> json) => OrderDetail(
      id: (json['id'] as num?)?.toInt(),
      orderCode: json['orderCode'] as String?,
      bidOrderId: (json['bidOrderId'] as num?)?.toInt(),
      bidOrderCode: json['bidOrderCode'] as String?,
      thirdOrderCode: json['thirdOrderCode'] as String?,
      userId: (json['userId'] as num?)?.toInt(),
      subCustomerId: (json['subCustomerId'] as num?)?.toInt(),
      orderStatus: (json['orderStatus'] as num?)?.toInt(),
      channelId: (json['channelId'] as num?)?.toInt(),
      barcode: json['barcode'] as String?,
      orderSource: json['orderSource'] as String?,
      orderTime: json['orderTime'] as String?,
      modelId: (json['modelId'] as num?)?.toInt(),
      imei: json['imei'] as String?,
      itemName: json['itemName'] as String?,
      skuId: json['skuId'] as String?,
      payStatus: (json['payStatus'] as num?)?.toInt(),
      payNo: json['payNo'] as String?,
      payAmount: (json['payAmount'] as num?)?.toDouble(),
      quoteAmount: (json['quoteAmount'] as num?)?.toDouble(),
      dealAmount: (json['dealAmount'] as num?)?.toDouble(),
      receiveTime: json['receiveTime'] as String?,
      receiveName: json['receiveName'] as String?,
      receivePhone: json['receivePhone'] as String?,
      receiveProvince: json['receiveProvince'] as String?,
      receiveCity: json['receiveCity'] as String?,
      receiveArea: json['receiveArea'] as String?,
      receiveAddress: json['receiveAddress'] as String?,
      orderRemark: json['orderRemark'] as String?,
      mark: (json['mark'] as num?)?.toInt(),
      checkStatus: (json['checkStatus'] as num?)?.toInt(),
      deletedFlag: (json['deletedFlag'] as num?)?.toInt(),
      createTime: json['createTime'] as String?,
      updateTime: json['updateTime'] as String?,
      offerId: (json['offerId'] as num?)?.toInt(),
      logisticsSendCount: (json['logisticsSendCount'] as num?)?.toInt(),
      resaleStatus: (json['resaleStatus'] as num?)?.toInt(),
      currentPage: (json['currentPage'] as num?)?.toInt(),
      pageSize: (json['pageSize'] as num?)?.toInt(),
      customerName: json['customerName'] as String?,
      orderLabelList: json['orderLabelList'] as List<dynamic>?,
      labelContentList: json['labelContentList'] as List<dynamic>?,
      reviewOrderAuditReportList: (json['reviewOrderAuditReportList']
              as List<dynamic>?)
          ?.map(
              (e) => ReviewOrderAuditReport.fromJson(e as Map<String, dynamic>))
          .toList(),
    );

Map<String, dynamic> _$OrderDetailToJson(OrderDetail instance) =>
    <String, dynamic>{
      'id': instance.id,
      'orderCode': instance.orderCode,
      'bidOrderId': instance.bidOrderId,
      'bidOrderCode': instance.bidOrderCode,
      'thirdOrderCode': instance.thirdOrderCode,
      'userId': instance.userId,
      'subCustomerId': instance.subCustomerId,
      'orderStatus': instance.orderStatus,
      'channelId': instance.channelId,
      'barcode': instance.barcode,
      'orderSource': instance.orderSource,
      'orderTime': instance.orderTime,
      'modelId': instance.modelId,
      'imei': instance.imei,
      'itemName': instance.itemName,
      'skuId': instance.skuId,
      'payStatus': instance.payStatus,
      'payNo': instance.payNo,
      'payAmount': instance.payAmount,
      'quoteAmount': instance.quoteAmount,
      'dealAmount': instance.dealAmount,
      'receiveTime': instance.receiveTime,
      'receiveName': instance.receiveName,
      'receivePhone': instance.receivePhone,
      'receiveProvince': instance.receiveProvince,
      'receiveCity': instance.receiveCity,
      'receiveArea': instance.receiveArea,
      'receiveAddress': instance.receiveAddress,
      'orderRemark': instance.orderRemark,
      'mark': instance.mark,
      'checkStatus': instance.checkStatus,
      'deletedFlag': instance.deletedFlag,
      'createTime': instance.createTime,
      'updateTime': instance.updateTime,
      'offerId': instance.offerId,
      'logisticsSendCount': instance.logisticsSendCount,
      'resaleStatus': instance.resaleStatus,
      'currentPage': instance.currentPage,
      'pageSize': instance.pageSize,
      'customerName': instance.customerName,
      'orderLabelList': instance.orderLabelList,
      'labelContentList': instance.labelContentList,
      'reviewOrderAuditReportList': instance.reviewOrderAuditReportList,
    };
